// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm1fOxs8Apj6yA0arBiTnAWIZ502dulqQ',
    appId: '1:1080577588331:web:f8a76b395af9b7c039452e',
    messagingSenderId: '1080577588331',
    projectId: 'energycelab',
    authDomain: 'energycelab.firebaseapp.com',
    databaseURL: 'https://energycelab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'energycelab.appspot.com',
    measurementId: 'G-ZED225X3MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLk9jArf048MuDu87t0z2aqdEHITUJ-4',
    appId: '1:1080577588331:android:e390912d465a1f4239452e',
    messagingSenderId: '1080577588331',
    projectId: 'energycelab',
    databaseURL: 'https://energycelab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'energycelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQb7FlSD1nb5XOPRioFcmDoZZPUEbGa0',
    appId: '1:1080577588331:ios:cf8a29a0374127c639452e',
    messagingSenderId: '1080577588331',
    projectId: 'energycelab',
    databaseURL: 'https://energycelab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'energycelab.appspot.com',
    iosClientId: '1080577588331-gruo9kp1gs041f3k0oh88imp26s24at0.apps.googleusercontent.com',
    iosBundleId: 'com.example.elow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQb7FlSD1nb5XOPRioFcmDoZZPUEbGa0',
    appId: '1:1080577588331:ios:aee1b3e3d28582a239452e',
    messagingSenderId: '1080577588331',
    projectId: 'energycelab',
    databaseURL: 'https://energycelab-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'energycelab.appspot.com',
    iosClientId: '1080577588331-hun2k87viqhjojg8rj5vjl8i72fa7kr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.elow.RunnerTests',
  );
}
